version: "3"
services:
  fmc:
    image: "chatopera/fmc:${FMC_BUILD:-develop}"
    restart: always
    volumes:
      - ./fmc/data/accounts.json:/app/config/accounts.json:ro
    ports:
      - "${FMC_PORT:-8555}:8555"
    environment:
      - DEBUG=${DEBUG:-}
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017/fmc}
      - BOT_PROVIDER=${BOT_PROVIDER:-https://bot.chatopera.com}
      - FAQ_SUGG_REPLY_THRESHOLD=${FAQ_SUGG_REPLY_THRESHOLD:-0}
    depends_on:
      - mongodb

  mongodb:
    image: "tutum/mongodb:3.2"
    restart: always
    volumes:
      - ./database/mongodb/data:/data/db
    ports:
      - "${MONGODB_PORT:-8556}:27017"
      - "${MONGODB_PORT2:-8557}:27018"
    environment:
      - AUTH=no
